version: '3.8'

services:
  web:
    container_name: health_server
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - mongo
    env_file:
      - ./configs/conf.env

  db:
    container_name: postgres_for_check
    restart: on-failure
    image: postgres:latest
    env_file:
      - ./configs/db.env
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - ./configs/mongo.env